### ISSUE TITLE
How to enable eth1 port ?

### ISSUE THREAD

**Issue by ghost** [MarvellEmbeddedProcessors/openwrt-bb#1]
I have a Clearfog A1 Rev2.1 board with OpenWRT BB system.

 Now I config the eth1 port with static address like 192.168.3.1, but I can not ping it from anther PC in the same address domain. So how should I config the eth1 port so that I can set up a connection ?

**Comment by ygvili** [comment]
Hi Xue Liu.

Are you describing U-boot environment?
If so, The U-boot cannot respond to ping.
To check the network is up try outgoing ping or TFTP.

If it is in linux, the system might be configured not to respond to ping.
Please see
https://linuxsupportz.wordpress.com/2012/11/25/enabledisable-ping-response/b

Thanks,
Yoav Gvili

**Comment by ghost** [comment]
Thank you for your reply.

I mean I have ping problem in Linux system.

The problem is that neither ping nor network connection can not work. For example I can not access the Luci interface via eth1 port.

**Comment by ygvili** [comment]
Can you ping out?

Yoav Gvili

**Comment by ghost** [comment]
Unfortunately, I can not ping out.

**Comment by ghost** [comment]
Some extra info:
When I plug and unplug Ethernet cable from eth1 there are no kernel info like:
eth1: link up, full duplex, speed 100 Mbps
or
eth1: link down

**Comment by gurumarvell** [comment]
At u-boot run dhcp or ping command so that the ethernet interface gets initialized first.  Once you do this ping will work from Linux.

**Comment by ghost** [comment]
Yes. Now it is working. ^_^
