### ISSUE TITLE
Any plan to update openwrt to cc ?

### ISSUE THREAD

**Issue by ghost** [MarvellEmbeddedProcessors/openwrt-bb#2]
Hello,

Is there any plan to update openwrt to latest release version CC ?

**Comment by lperkov** [comment]
Hi there,

support for the Marvell and SolidRun boards can already be found in mainline OpenWrt CC and trunk. Is there any specific reason why you would like to use CC in this repository?

I do not know what are Marvell plans when it comes to CC and later OpenWrt releases.

**Comment by ghost** [comment]
Hello,

Thank you for your feedback.
