### ISSUE TITLE
openwrt-bb fails to build for ClearFog A1

### ISSUE THREAD

**Issue by david0fc** [MarvellEmbeddedProcessors/openwrt-bb#3]
Following the instructions literally, except for the root folder, which is in my home, rather than in /opt, I get:

`...`
`# Align the squashfs image size before calling the profiles,`
`# otherwise the size would keep growing`
`/home/dfernandez/src/Marvell/marvell-openwrt-bb/staging_dir/host/bin/padjffs2 /home/dfernandez/src/Marvell/marvell-openwrt-bb/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-mvebu/root.squashfs 4 8 16 64 128 256`
`padding image to 00418000`
`padding image to 00420000`
`padding image to 00440000`
`dd if=/home/dfernandez/src/Marvell/marvell-openwrt-bb/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-mvebu/root.squashfs of=/home/dfernandez/src/Marvell/marvell-openwrt-bb/bin/mvebu/openwrt-mvebu-root.squashfs bs=128k conv=sync`
`34+1 records in`
`35+0 records out`
`4587520 bytes (4.6 MB) copied, 0.00465086 s, 986 MB/s`
`dd if=/home/dfernandez/src/Marvell/marvell-openwrt-bb/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-mvebu/root.ubifs of=/home/dfernandez/src/Marvell/marvell-openwrt-bb/bin/mvebu/openwrt-mvebu-root.ubifs bs=128k conv=sync`
`dd: failed to open '/home/dfernandez/src/Marvell/marvell-openwrt-bb/build_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/linux-mvebu/root.ubifs': No such file or directory`
`Makefile:182: recipe for target 'install' failed`
`make[5]: *** [install] Error 1`
`make[5]: Leaving directory '/home/dfernandez/src/Marvell/marvell-openwrt-bb/target/linux/mvebu/image'`
`Makefile:22: recipe for target 'install' failed`
`make[4]: *** [install] Error 2`
`make[4]: Leaving directory '/home/dfernandez/src/Marvell/marvell-openwrt-bb/target/linux/mvebu'`
`Makefile:13: recipe for target 'install' failed`
`make[3]: *** [install] Error 2`
`make[3]: Leaving directory '/home/dfernandez/src/Marvell/marvell-openwrt-bb/target/linux'`
`target/Makefile:21: recipe for target 'target/linux/install' failed`
`make[2]: *** [target/linux/install] Error 2`
`make[2]: Leaving directory '/home/dfernandez/src/Marvell/marvell-openwrt-bb'`
`target/Makefile:17: recipe for target '/home/dfernandez/src/Marvell/marvell-openwrt-bb/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/stamp/.target_install' failed`
`make[1]: *** [/home/dfernandez/src/Marvell/marvell-openwrt-bb/staging_dir/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi/stamp/.target_install] Error 2`
`make[1]: Leaving directory '/home/dfernandez/src/Marvell/marvell-openwrt-bb'`
`/home/dfernandez/src/Marvell/marvell-openwrt-bb/include/toplevel.mk:171: recipe for target 'world' failed`
`make: *** [world] Error 2`

Any ideas or things that I should try?

**Comment by david0fc** [comment]
The problem seems to be that there are either:
- No options set for $($(PROFILE)_UBIFS_OPTS) and $(UBIFS_OPTS)
  or
- The $(call Image/Build,ubifs) inside Image/mkfs/ubifs should be inside a conditional for the above variables being both empty too.

I can make it build by doing:
`--- a/include/image.mk`
`+++ b/include/image.mk`
`@@ -198,8 +198,10 @@ ifneq ($(CONFIG_TARGET_ROOTFS_UBIFS),)`
` `
`     define Image/mkfs/ubifs`
` `
`\-        ifneq ($($(PROFILE)_UBIFS_OPTS)$(UBIFS_OPTS),)`
`\+        # ifneq ($($(PROFILE)_UBIFS_OPTS)$(UBIFS_OPTS),)`
`                $(STAGING_DIR_HOST)/bin/mkfs.ubifs `
`+                       $(if $($(PROFILE)_UBIFS_OPTS)$(UBIFS_OPTS),, \`
`+                               -m 512 -e  128KiB -c 100) \`
`$(if $($(PROFILE)_UBIFS_OPTS), \`
`$(shell echo $($(PROFILE)_UBIFS_OPTS)), \`
`$(shell echo $(UBIFS_OPTS)) \`
`@@ -212,7 +214,7 @@ ifneq ($(CONFIG_TARGET_ROOTFS_UBIFS),)`
`--squash-uids \`
`-o $(KDIR)/root.ubifs \`
`-d $(TARGET_DIR)`
`-        endif`
`+        # endif`
`$(call Image/Build,ubifs)`
` `
`         ifneq ($($(PROFILE)_UBI_OPTS)$(UBI_OPTS),)`

But this might not be the correct solution... Would be good if some maintainer provides one.

**Comment by v-vid** [comment]
Hi David,

Can you please try removing the ubifs from the Target images in the make menuconfig.
Ubifs is intended to work on top of raw flash, not block devices.

**Comment by david0fc** [comment]
On 07/04/16 16:59, Vladimir Vid wrote:

> Hi David,
> 
> Can you please try removing the ubifs from the Target images in the 
> make menuconfig.
> Ubifs is intended to work on top of raw flash, not block devices.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/MarvellEmbeddedProcessors/openwrt-bb/issues/3#issuecomment-206969104
> 
> Yes, that fixes it, although it is a flaw in the build system.

By the way, I'm trying to boot in the same way in openwrt-dd, but the 
VFS seems unable to recognize the ext4 partition, despite adding the 
ext4 filesystem to the kernel. It was trying to open it with ubifs 
(failing), and when removing the ubifs, it does not try any other 
filesystem and fails straight away.

The mmcblk0p1 is recognized in openwrt if booting with the ramdisk image.

Is there something obvious that you could suggest?

Regards
David F.

**Comment by lperkov** [comment]
The OpenWrt trunk at the moment supports only initramfs images and uses mainline kernel. This is not related to this Marvell fork.

We will add proper support for ClearFog in mainline OpenWrt in the near future. Let us know if there are any other issues with this specific project or we can close the issue.

**Comment by david0fc** [comment]
On 07/04/16 22:51, Luka Perkov wrote:

> The OpenWrt trunk at the moment supports only initramfs images and 
> uses mainline kernel. This is not related to this Marvell fork.
> 
> We will add proper support for ClearFog in mainline OpenWrt in the 
> near future.
> 
> Sorry for the off-topic.

Anyway, seems that the reason why I could not mount the root from mmc 
was because the kernel boot options where set to add the dtb to the 
zimage, and that prevents somehow the kernel from mounting the ext4 in mmc.

As for the ramdisk, everything is put in a final file, it would be good 
to have both zimages generated, so that we can do ramdisk boot and ext4 
root.

**Comment by v-vid** [comment]
I'm glad you have sorted it out.

We will take a further look to see why this is happening, but as Luka said, 
support on trunk version is still work in progress and some features are not yet fully implemented/finished.

Regards,
Vladimir
